"""empty message

Revision ID: c2c85a7f9142
Revises: 2eaf92a9dcc5
Create Date: 2024-06-02 22:29:19.050499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c85a7f9142'
down_revision = '2eaf92a9dcc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=5), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
